import { globby } from 'globby';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// Root is ../../.. from packages/agent/scripts based on monorepo root structure
const ROOT_DIR = path.resolve(__dirname, '../../..');

async function generate() {
    // Look for agent files in apps/backend/modules/*/src/agent/*.ts
    // This aligns with user's project structure where business logic is in apps/backend/modules
    const agentFiles = await globby('apps/backend/modules/*/src/agent/*.ts', { cwd: ROOT_DIR });

    const agents = await Promise.all(
        agentFiles.map(async (file) => {
            // file path example: apps/backend/modules/orchestrator-api/src/agent/EchoProcessor.ts
            const parts = file.split('/');
            // parts: ['apps', 'backend', 'modules', 'orchestrator-api', 'src', 'agent', 'EchoProcessor.ts']
            const moduleName = parts[3]; // 'orchestrator-api'
            const fileName = path.basename(file, '.ts');

            // key format: moduleName.AgentName
            const key = `${moduleName}.${fileName}`;

            // import path relative to packages/agent/src/registry.ts
            // registry.ts is in packages/agent/src
            // file is in apps/backend/modules/...
            // so ../../../ to root, then file
            const importPath = `../../../${file.replace('.ts', '.js')}`;

            const variableName = `${moduleName}_${fileName}`.replace(/-/g, '_');

            const fileContent = await fs.readFile(path.join(ROOT_DIR, file), 'utf-8');
            const type = fileContent.includes('extends PersistentAgent') ? 'persistent' : 'job';

            return { key, variableName, importPath, type };
        }),
    );

    const jobAgents = agents.filter((a) => a.type === 'job');
    const persistentAgents = agents.filter((a) => a.type === 'persistent');

    // For job agents, import the class directly (not an instance)
    // For persistent agents, import the class directly too
    const imports = agents
        .map((a) => {
            const parts = a.key.split('.');
            const fileName = parts[1];
            // Convert fileName from PascalCase to PascalCase (start upper) if needed, usually it is.
            // But let's follow existing logic: Split by '-' (if filename has dashes) and capitalize each part.
            // But fileName comes from path.basename, e.g. 'EchoProcessor'
            // Existing logic was: 
            // fileName.split('-').map(part => Capitalize).join('')
            // This handles 'my-agent.ts' -> 'MyAgent'.
            const originalClassName = fileName
                .split('-')
                .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
                .join('');

            const prefixedClassName = a.variableName
                .split('_')
                .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
                .join(''); // e.g. OrchestratorApi_EchoProcessor -> OrchestratorApiEchoProcessor

            return `import { ${originalClassName} as ${prefixedClassName} } from '${a.importPath}';`;
        })
        .join('\n');

    // Generate class name for mappings
    const toClassName = (varName: string) =>
        varName
            .split('_')
            .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
            .join('');

    const jobMapping = jobAgents
        .map((a) => `  '${a.key}': ${toClassName(a.variableName)},`)
        .join('\n');
    const persistentMapping = persistentAgents
        .map((a) => `  '${a.key}': ${toClassName(a.variableName)},`)
        .join('\n');

    // Logic for imports:
    // We need to import JobProcessor/PersistentAgent types.
    // Since we are inside packages/agent, we can import from '.' or './core'.
    // registry.ts will likely be in src/registry.ts.
    // The types are likely in src/core/processor.ts and src/core/persistent.ts
    // So './core/processor.js' and './core/persistent.js' is correct relative to src/registry.ts.

    const content = `// This file is auto-generated by scripts/generate.ts
import type { JobProcessor, ProcessorConfig } from './core/processor.js';
import type { PersistentAgent } from './core/persistent.js';

${imports}

// Job processors are class constructors that accept ProcessorConfig
export const jobProcessors: Record<string, new (config: ProcessorConfig) => JobProcessor<unknown>> = {
${jobMapping}
};

// Persistent agents are class constructors (no config in constructor)
export const processors: Record<string, new () => PersistentAgent> = {
${persistentMapping}
};
`;

    const outputPath = path.join(ROOT_DIR, 'packages/agent/src/registry.ts');

    // Ensure directory exists
    await fs.mkdir(path.dirname(outputPath), { recursive: true });

    await fs.writeFile(outputPath, content);
    console.info(`Generated Agent registry at ${outputPath}`);
}

generate().catch(console.error);
